name: ht_shared
description: Shared utilities and models.
version: 1.0.0
publish_to: none
repository: https://github.com/Headlines-Toolkit/ht-shared

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
